name: UAMP Build with MPLAB X and XC32
description: This action builds a MPLAB X / XC32 project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  mplabx_version:
    description: Version of MPLAB X to use
    required: true
    default: "6.30"
  xc32_version:
    description: Version of the XC32 compiler to use
    required: true
    default: "5.00"
  dfp_packs:
    description: DFP packs to install
    required: false
    default: ""
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: default
runs:
  using: docker
  image: Dockerfile
  env:
    MPLABX_VERSION: ${{ inputs.mplabx_version }}
    XC32_VERSION: ${{ inputs.xc32_version }}
    DFP_PACKS: ${{ inputs.dfp_packs }}
    PROJECT: ${{ inputs.project }}
    CONFIGURATION: ${{ inputs.configuration }}
    JAVA_TOOL_OPTIONS: "-Xmx4g -XX:+UseG1GC"

